### ISSUE TITLE
Notification are blank

### ISSUE THREAD

**Issue by Venutius** [henrywright/crowdmentions#1]
This continues the conversation we were having on the bp forum.

I'm not getting the notifications, but they are blank, the notification drop down is blank and when you go to view the notifications they are blank and there is no content to read.

**Comment by henrywright** [comment]
Can you let me know:

 - Which theme you're using?
 - Were you using the @group or @mod command?
 - Did you post a group update or did you comment on a group update?
 - Are there group members and moderators in the group?
 - Are you using the latest version of the plugin? I pushed some changes earlier

Also just to note while in testing phase, if you update the plugin, be sure to delete old notifications from earlier tests

**Comment by Venutius** [comment]
On 16 October 2015 at 18:11 Henry Wright <notifications@github.com> wrote:Can you let me know:Which theme you're using? Currently on 2015, planning to move to GrapheneWere you using the @group or @mod command? BothDid you post a group update or did you comment on a group update?Posted group updateAre there group members and moderators in the group?YesAre you using the latest version of the plugin? I pushed some changes earlier Not yet but do not think you have covered this one yetAlso just to note while in testing phase, if you update the plugin, be sure to delete old notifications from earlier tests—Reply to this email directly or view it on GitHub.

**Comment by henrywright** [comment]
I think the reason you're seeing blank notifications is because you're using an old version. You'll need to clear those old notifications by either marking them as read or deleting them and then install the latest version.

**Comment by Venutius** [comment]
No I've just loaded the latest version, no change.On 16 October 2015 at 18:53 Henry Wright <notifications@github.com> wrote:I think the reason you're seeing blank notifications is because you're using an old version. You'll need to clear those old notifications by either marking them as read or deleting them and then install the latest version.—Reply to this email directly or view it on GitHub.

**Comment by Venutius** [comment]
I had 7 plugins loaded and would you believe one of those was stopping it from working. Not sure which one yetOn 16 October 2015 at 18:53 Henry Wright <notifications@github.com> wrote:I think the reason you're seeing blank notifications is because you're using an old version. You'll need to clear those old notifications by either marking them as read or deleting them and then install the latest version.—Reply to this email directly or view it on GitHub.

**Comment by Venutius** [comment]
Seems to stop working at the moment with bbPress installed, most oddOn 16 October 2015 at 18:53 Henry Wright <notifications@github.com> wrote:I think the reason you're seeing blank notifications is because you're using an old version. You'll need to clear those old notifications by either marking them as read or deleting them and then install the latest version.—Reply to this email directly or view it on GitHub.

**Comment by Venutius** [comment]
Hi Henry, It does seem to be bbPress that causes crowdmentions to fail to work on it's own, and to cause it to send blank notifications when used with both Mediapress and bbPress though on its own Mediapress works fine.On 16 October 2015 at 18:53 Henry Wright <notifications@github.com> wrote:I think the reason you're seeing blank notifications is because you're using an old version. You'll need to clear those old notifications by either marking them as read or deleting them and then install the latest version.—Reply to this email directly or view it on GitHub.

**Comment by henrywright** [comment]
Ah yes, sometimes plugins can interfere with each other! I'll test against bbPress and see if I notice anything odd. In the mean time, grateful if you could let me know if you manage to pin down the problem to a particular plugin

**Comment by henrywright** [comment]
Confirmed. Notifications are blank if bbPress is installed.
